apiVersion: v1
kind: Service
metadata:
  name: {{$.Values.deployment.repository}}
  labels:
    app: {{$.Values.deployment.repository}}
spec:
  selector:
    app: {{$.Values.deployment.repository}}
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80